[package]
name = "path"
version = "0.1.0"
authors = ["ruko <rukokarasu@gmail.com>"]

[dependencies]
bvh = "0.3.2"
nalgebra = "0.20.0"
png = "0.12.0"
rand = "0.5.5"
alga = "0.9.3"
nom = "5.0.1"
tobj = "2.0.3"
